AWSTemplateFormatVersion: 2010-09-09
Parameters:
  pTGWSubnetId:
    Type: String
  pUbuntuAMIId:
    Type: AWS::EC2::Image::Id
    Description: The baseline Ubuntu image ID.
  pRHELIAMIId:
    Type: AWS::EC2::Image::Id
    Description: The baseline AMI ID (used for the other central services EC2s)
  pALMsampleMIId:
    Type: AWS::EC2::Image::Id
    Description: The baseline AMI ID.
  pRHEL9IAMIId:
    Type: AWS::EC2::Image::Id
    Description: The baseline AMI ID (used for the other central services EC2s)
  pRHEL10IAMIId:
    Type: AWS::EC2::Image::Id
    Description: The baseline AMI ID (used for the other central services EC2s)
  pAWSAMIId:
    Type: AWS::EC2::Image::Id
    Description: The baseline AWS image ID (used for the Bastion EC2).
  pEnvironment:
    Type: String
    Description: Development? Test Upstream? Prod Upstream?
    AllowedValues:
      - dev
      - upprod
      - uptest
  pDomain:
    Description: The domain representing the environment (ex. sample.sample.dev or sample.sample.dev).
    Type: String
    AllowedValues:
      - sample
      - sample
  pDeployWorkspaces:
    Description: Deploy AWS Workspaces infrastructure template.
    Type: String
    AllowedValues:
      - "true"
      - "false"
  pDeployWorkspace:
    Description: Deploy the Workspace resource from within the Workspaces template.
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  pDeployEC2s:
    Description: Deploy the Central Services EC2s
    Type: String
    AllowedValues:
      - "true"
      - "false"
  pSampleEnv:
    Type: String
    Description: Production? Test?
    AllowedValues:
      - prod
      - test
  pInstanceType:
    Description: EC2 instance type for the central service EC2s.
    Type: String
    AllowedValues:
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5n.large
      - c5n.xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c6i.large
      - c6i.xlarge
      - c6in.2xlarge
      - c6in.4xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5n.large
      - m5n.xlarge
      - m5n.2xlarge
      - m5n.4xlarge
      - m6i.xlarge
      - r4.large
      - r4.xlarge
      - r5.large
      - r5.xlarge
      - r6i.xlarge
      - r6i.2xlarge
      - r6i.4xlarge
      - r6i.8xlarge
      - r6i.12xlarge
      - r6in.xlarge
      - r6in.2xlarge
      - r6in.4xlarge
      - r6in.8xlarge
      - r6in.12xlarge
      - r7i.large
      - r7i.xlarge
      - t2.small (Testing / Not for Production Use)
      - t2.medium
      - t2.large
      - t3.small (Testing / Not for Production Use)
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - t3a.medium
    ConstraintDescription: Please choose a valid EC2 instance type
  pArmInstanceType:
    Type: String
  pVpcId:
    Description: The ID of the VPC.
    Type: AWS::EC2::VPC::Id
  pTGWId:
    Description: The ID of the Transit Gateway.
    Type: String
  pSubnetCidrA:
    Description: The CIDR of the first subnet.
    Type: String
  pSubnetCidrB:
    Description: The CIDR of the second subnet.
    Type: String
  pSubnetCidrC:
    Description: The CIDR of the second subnet.
    Type: String
  pSubnetCidrD:
    Description: The CIDR of the second subnet.
    Type: String
  pSubnetCidrE:
    Description: The CIDR of the second subnet.
    Type: String
  pSubnetCidrG:
    Description: The CIDR of the second subnet.
    Type: String
  pSubnetCidrF:
    Description: The CIDR of the second subnet.
    Type: String
  pVpcCidr:
    Description: The first CIDR of the VPC.
    Type: String
  pVpcCidr1:
    Description: If exists, the second CIDR of the VPC.
    Type: String
  pVpcCidr2:
    Description: If exists, the second CIDR of the VPC.
    Type: String
    Default: "192.168.1.1/32"
  pVpcCidr3:
    Description: If exists, the second CIDR of the VPC.
    Type: String
    Default: "192.168.1.2/32"
  pVpcCidr4:
    Description: If exists, the second CIDR of the VPC.
    Type: String
    Default: "192.168.1.3/32"
  pEc2DailyStop:
    Type: String
    Description: Do you want the EC2 resources to stop automatically Monday-Friday at 10PM EST, 7PM PST?
    AllowedValues:
      - "true"
      - "false"
  pEc2DailyStart:
    Type: String
    Description: Do you want the EC2 resources to stop automatically Monday-Friday at 4AM EST, 1AM PST?
    AllowedValues:
      - "true"
      - "false"
  pUpTestCIDR0:
    Type: String
    Default: 192.168.1.1/32
  pUpTestCIDR1:
    Type: String
    Default: 192.168.1.2/32
  pUpProdCIDR0:
    Type: String
    Default: 192.168.1.3/32
  pUpProdCIDR1:
    Type: String
    Default: 192.168.1.4/32
  pPeeringIdUpTest:
    Type: String
    Default: "null"
  pPeeringIdUpProd:
    Type: String
    Default: "null"
  pUptestResolverIP0:
    Type: String
    Default: "0.0.0.0/0"
  pUptestResolverIP1:
    Type: String
    Default: "0.0.0.0/0"
  pUpprodResolverIP0:
    Type: String
    Default: "0.0.0.0/0"
  pUpprodResolverIP1:
    Type: String
    Default: "0.0.0.0/0"
  pDirectoryId:
    Type: String
    Default: "null"
  pDevCidr0:
    Type: String
    Default: 192.168.1.0/32
  pDevCidr1:
    Type: String
    Default: 192.168.1.1/32
  pDevCidr2:
    Type: String
    Default: 192.168.1.2/32
  pDevCidr3:
    Type: String
    Default: 192.168.1.3/32
  pDevCidr4:
    Type: String
    Default: 192.168.1.4/32
  pUpprodPeeringID:
    Type: String
    Default: "null"
  pUptestPeeringID:
    Type: String
    Default: "null"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Information"
        Parameters:
          - pSampleEnv
          - pEnvironment
          - pDomain
      - Label:
          default: "Host Information"
        Parameters:
          - pRHELIAMIId
          - pAWSAMIId
          - pUbuntuAMIId
          - pInstanceType
    ParameterLabels:
      pSampleEnv:
        default: "sample Environment"
      pEnvironment:
        default: "Deployment Environment"
      pDomain:
        default: "Deployment Domain"
      pInstanceType:
        default: "Instance Type"
      pAWSAMIId:
        default: "Amazon Linux AMI ID"
      pUbuntuAMIId:
        default: "Ubuntu AMI ID"
Conditions:
  DeployWorkspaces: !Equals
    - !Ref pDeployWorkspaces
    - "true"
  DeployEC2s: !Equals
    - !Ref pDeployEC2s
    - "true"
  Dev: !Equals
    - !Ref pEnvironment
    - dev
  Upstream: !Or
    - !Equals
      - upprod
      - !Ref pEnvironment
    - !Equals
      - uptest
      - !Ref pEnvironment
  Production: !Equals
    - !Ref pSampleEnv
    - "prod"
Resources:
  sampleCentralServicesNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesNetwork.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pSubnetCidrA: !Ref pSubnetCidrA
        pSubnetCidrB: !Ref pSubnetCidrB
        pSubnetCidrC: !Ref pSubnetCidrC
        pSubnetCidrD: !Ref pSubnetCidrD
        pSubnetCidrE: !Ref pSubnetCidrE
        pSubnetCidrF: !Ref pSubnetCidrF
        pSubnetCidrG: !Ref pSubnetCidrG
        pTGWId: !Ref pTGWId
        pSampleEnv: !Ref pSampleEnv
        pVpcId: !Ref pVpcId
        pVpcCidr: !Ref pVpcCidr
        pVpcCidr1: !Ref pVpcCidr1
        pVpcCidr2: !Ref pVpcCidr2
        pVpcCidr3: !Ref pVpcCidr3
        pVpcCidr4: !Ref pVpcCidr4
        pUpTestCIDR0: !Ref pUpTestCIDR0
        pUpTestCIDR1: !Ref pUpTestCIDR1
        pUpProdCIDR0: !Ref pUpProdCIDR0
        pUpProdCIDR1: !Ref pUpProdCIDR1
        pPeeringIdUpTest: !Ref pPeeringIdUpTest
        pPeeringIdUpProd: !Ref pPeeringIdUpProd
        pDevCidr0: !Ref pDevCidr0
        pDevCidr1: !Ref pDevCidr1
        pDevCidr2: !Ref pDevCidr2
        pDevCidr3: !Ref pDevCidr3
        pDevCidr4: !Ref pDevCidr4
        pUpprodPeeringID: !Ref pUpprodPeeringID
        pUptestPeeringID: !Ref pUptestPeeringID
  sampleCentralServicesDevNLB:
    Type: AWS::CloudFormation::Stack
    Condition: Dev
    DependsOn:
      - sampleCentralServicesDNS
      - sampleCentralServicesEC2s
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesDevNLB.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pSampleEnv: !Ref pSampleEnv
        pBuilderIp: !GetAtt sampleCentralServicesEC2s.Outputs.builderEC2IPOutput
        pDomain: !Ref pDomain
  sampleCentralServicesNLB:
    Type: AWS::CloudFormation::Stack
    Condition: Upstream
    DependsOn: sampleCentralServicesDNS
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesNLB.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pSampleEnv: !Ref pSampleEnv
        pDomain: !Ref pDomain
  sampleCentralServicesEndpoints:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - sampleCentralServicesNetwork
      - sampleCentralServicesDNS
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesEndpoints.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pSampleEnv: !Ref pSampleEnv
        pSubnetsampleZId: !GetAtt sampleCentralServicesNetwork.Outputs.sampleCentralServicesSubnetsampleZId
        pDomain: !Ref pDomain
  sampleCentralServicesWorkspaces:
    Condition: DeployWorkspaces
    DependsOn: sampleCentralServicesNetwork
    DeletionPolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesWorkspaces.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pSampleEnv: !Ref pSampleEnv
        pDirectoryId: !Ref pDirectoryId
        pRoute53ID: !GetAtt sampleCentralServicesDNS.Outputs.sampleCentralServicesRoute53Zone
  sampleCentralServicesDNS:
    DependsOn:
      - sampleCentralServicesNetwork
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesDNS.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pDomain: !Ref pDomain
        pSampleEnv: !Ref pSampleEnv
        pUptestResolverIP0: !Ref pUptestResolverIP0
        pUptestResolverIP1: !Ref pUptestResolverIP1
        pUpprodResolverIP0: !Ref pUpprodResolverIP0
        pUpprodResolverIP1: !Ref pUpprodResolverIP1
  sampleCentralServicesAMI:
    DependsOn: sampleCentralServicesNetwork
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesAMI.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pInstanceType: !Ref pInstanceType
        pArmInstanceType: !Ref pArmInstanceType
        pRHELIAMIId: !Ref pRHELIAMIId
        pALMsampleMIId: !Ref pALMsampleMIId
        pRHEL9IAMIId: !Ref pRHEL9IAMIId
        pRHEL10IAMIId: !Ref pRHEL10IAMIId
        pAWSAMIId: !Ref pAWSAMIId
        pSampleEnv: !Ref pSampleEnv
        pUbuntuAMIId: !Ref pUbuntuAMIId
  sampleCentralServicesEC2s:
    Condition: DeployEC2s
    DependsOn:
      - sampleCentralServicesDNS
      - sampleCentralServicesAMI
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesEC2.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pInstanceType: !Ref pInstanceType
        pDomain: !Ref pDomain
        pSampleEnv: !Ref pSampleEnv
        pEc2DailyStop: !Ref pEc2DailyStop
        pEc2DailyStart: !Ref pEc2DailyStart
        pRoute53ID: !GetAtt sampleCentralServicesDNS.Outputs.sampleCentralServicesRoute53Zone
  sampleCentralServicesWindowsCA:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - sampleCentralServicesEC2s
    Condition: Dev
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesWindowsCA.yaml
      Parameters:
        AdministratorSecret: "arn:aws-us-gov:secretsmanager:us-gov-west-1:361925695366:secret:dc/certificateauth/certAdmin-qdcYjY"
        EntCaServerSubnet: !Sub "{{resolve:ssm:/sample/vpc/sample-${pEnvironment}-${pSampleEnv}-vpc/sample-central-services-subnet/e/id}}"
        DirectoryType: AWSManaged
        DomainController1IP: "10.4.182.199"
        DomainController2IP: "10.4.182.222"
        DomainDNSName: "directory.dev.dev"
        DomainNetBIOSName: "directory"
        VPCCIDR: !Ref pVpcCidr3
        VPCID: !Ref pVpcId
        KeyPairName: sample-central-services
        pRoute53ID: !GetAtt sampleCentralServicesDNS.Outputs.sampleCentralServicesRoute53Zone
  sampleCentralServicesS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesS3.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pDomain: !Ref pDomain
        pSampleEnv: !Ref pSampleEnv
  sampleCentralServicesLogging:
    Type: AWS::CloudFormation::Stack
    Condition: Production
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesLogging.yaml
  sampleCentralServicesSystemManager:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicesSystemManager.yaml
  sampleCentralServicsLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://sample-${pSampleEnv}-${pEnvironment}-cloud-formation-templates.s3.us-gov-west-1.amazonaws.com/sampleCentralServices/childTemplates/sampleCentralServicsLambda.yaml
      Parameters:
        pEnvironment: !Ref pEnvironment
        pSampleEnv: !Ref pSampleEnv
Outputs:
  ec2DefaultKeyOutput:
    Condition: DeployEC2s
    Description: The name of the Parameter in the Parameter Store that contains the EC2-user private key.
    Value: !Sub /ec2/keypair/${sampleCentralServicesEC2s.Outputs.ec2DefaultKeyOutput}
