Resources:
  cloudtrailS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "cloudtrail-${AWS::AccountId}-multiregional-bucket"
  cloudtrailS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref cloudtrailS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws-us-gov:s3:::cloudtrail-${AWS::AccountId}-multiregional-bucket
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws-us-gov:s3:::cloudtrail-${AWS::AccountId}-multiregional-bucket/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  cloudTrailTrailKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: cloudtrail encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action:
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey"
              - "kms:GenerateDataKeyWithoutPlaintext"
            Resource: "*"
            Condition:
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:${AWS::Partition}:cloudtrail:*:${AWS::AccountId}:trail/*
                aws:SourceArn: !Sub arn:${AWS::Partition}:cloudtrail:*:${AWS::AccountId}:trail/*
  cloudTrailTrailCloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - cloudTrailTrailKMSKey
      - cloudtrailS3BucketPolicy
    Properties:
      IncludeGlobalServiceEvents: true
      EventSelectors:
        - IncludeManagementEvents: true
          DataResources: []
          ReadWriteType: All
          ExcludeManagementEventSources: []
      IsMultiRegionTrail: true
      AdvancedEventSelectors: []
      S3BucketName: !Ref cloudtrailS3Bucket
      TrailName: !Sub "cloudtrail-${AWS::AccountId}-multiregional-bucket"
      EnableLogFileValidation: false

      IsLogging: true
      IsOrganizationTrail: false
      InsightSelectors: []
      KMSKeyId: !Ref cloudTrailTrailKMSKey
