AWSTemplateFormatVersion: 2010-09-09
Parameters:
  pEnvironment:
    Type: String
    Description: Development? Test Upstream? Prod Upstream?
    AllowedValues:
      - dev
      - upprod
      - uptest
  pSAMPLEEnv:
    Type: String
    Description: Production? Test?
    AllowedValues:
      - prod
      - test
Resources:
  lambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Sub sample-${pSAMPLEEnv}-${pEnvironment}-cloud-formation-templates
        S3Key: supportingFiles/lambda/lambdaLayer/lambda_layers.zip
      Description: 3.9 Layer
      LayerName: sample-lambda-layer
  lambdaLayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/sample/lambda/layers/sample-lambda-layer/arn"
      Type: String
      Value: !Ref lambdaLayer
      Description: SSM Parameter for lambdaLayer latest version number.