AWSTemplateFormatVersion: 2010-09-09
Parameters:
  pSampleEnv:
    Type: String
    Description: Production? Test?
    AllowedValues:
      - prod
      - test
  pEnvironment:
    Type: String
    Description: Development? Test Upstream? Prod Upstream?
    Default: dev
    AllowedValues:
      - dev
      - upprod
      - uptest
  pDirectoryId:
    Type: String
  pRoute53ID:
    Type: String
Resources:
  WorkspacesDefaultRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - workspaces.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Workspaces-Default-Role
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonWorkSpacesServiceAccess
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonWorkSpacesSelfServiceAccess
      RoleName: workspaces_DefaultRole #Do not customize.  This specific name is required.
# Create Lambda function to register Managed AD/AD Connector with Workspaces
  RegisterDirectory:
    Type: AWS::Lambda::Function
    DependsOn: WorkspacesDefaultRole
    Properties:
      Code:
        ZipFile: |
          import logging
          import boto3
          import json
          import cfnresponse as cfn
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          workspaces = boto3.client('workspaces')
          def lambda_handler(event, context):
            DirectoryId = event['ResourceProperties']['Directory_Id']
            SubnetId1 = event['ResourceProperties']['Subnet_Id1']
            SubnetId2 = event['ResourceProperties']['Subnet_Id2']
            try:
              response = workspaces.register_workspace_directory(DirectoryId=DirectoryId,SubnetIds=[SubnetId1,SubnetId2])
              print('Successfully Registered Directory')
              cfn.send(event, context, cfn.SUCCESS, {"Message": "Directory Registration successful!"})
              logger.info('SUCCESS!')
            except Exception as e:
              print("Error: " + str(e))
              logger.info('FAILED! - Exception during Directory Registration')
              cfn.send(event, context, cfn.FAILED, {"Message": "Directory Registration NOT successful!"})
            return
      Role: !GetAtt RegistrationExecutionRole.Arn
      Description: Register Managed AD with Workspaces
      Handler: index.lambda_handler
      Runtime: python3.9
      Timeout: 90
      FunctionName: 'WorkspaceRegistration'
# Create IAM Role for Lambda function to register Managed AD/AD Connector with Workspaces
  RegistrationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Description: Role for Lambda Execution of Workspace Directory Registration
      RoleName: 'WorkspaceRegistrationExecutionRole'
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSDirectoryServiceFullAccess
        - "arn:aws-us-gov:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: DirectoryRegistration
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - workspaces:RegisterWorkspaceDirectory
                  - iam:GetRole
                  - ec2:Describe*
                  - workdocs:RegisterDirectory
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                Resource: !Sub arn:${AWS::Partition}:logs:region:account-id:*
# Invoke the Lambda function to register Managed AD/AD Connector with Workspaces
  RegisterDirectoryInvoke:
    Type: Custom::RegisterDirector
    DeletionPolicy: Retain
    Properties:
      ServiceTimeout: 300
      ServiceToken: !GetAtt RegisterDirectory.Arn
      FunctionName: 'WorkspaceRegistration'
      Directory_Id: !Ref pDirectoryId
      Subnet_Id1: !Sub "{{resolve:ssm:/sample/vpc/sample-${pEnvironment}-${pSampleEnv}-vpc/sample-central-services-subnet/d/id}}"
      Subnet_Id2: !Sub "{{resolve:ssm:/sample/vpc/sample-${pEnvironment}-${pSampleEnv}-vpc/sample-central-services-subnet/c/id}}"
  WindowsFileSystemSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SMB access
      VpcId: !Sub "{{resolve:ssm:/sample/vpc/sample-${pEnvironment}-${pSampleEnv}-vpc/id}}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "445"
          ToPort: "445"
          SourcePrefixListId: !Sub "{{resolve:ssm:/sample/vpc/cidr/prefix}}"
  WindowsFileSystem:
    Type: 'AWS::FSx::FileSystem'
    Properties:
      FileSystemType: WINDOWS
      StorageCapacity: 2000
      StorageType: SSD
      SubnetIds:
        - !Sub "{{resolve:ssm:/sample/vpc/sample-${pEnvironment}-${pSampleEnv}-vpc/sample-central-services-subnet/d/id}}"
      SecurityGroupIds:
        - !Ref WindowsFileSystemSecurityGroup
      Tags:
        - Key: deploymentType
          Value: centralServices
        - Key: Name
          Value: !Sub fsx.${pEnvironment}.${pDomain}.dev
      WindowsConfiguration:
        ActiveDirectoryId: !Ref pDirectoryId
        ThroughputCapacity: 16
        Aliases:
            - !Sub fsx.${pEnvironment}.${pDomain}.dev
        WeeklyMaintenanceStartTime: '7:16:30'
        DailyAutomaticBackupStartTime: '01:00'
        AutomaticBackupRetentionDays: 90
        DeploymentType: SINGLE_AZ_2
        CopyTagsToBackups: true
  WindowsFileSystemRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Alias record for the API server
      HostedZoneId: !Ref pRoute53ID
      RecordSets:
        - Name: !Sub "fsx.${pEnvironment}.${pDomain}.dev"
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !GetAtt WindowsFileSystem.DNSName
  DirectoryHostRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref pRoute53ID
      Name: !Sub "directory.${pEnvironment}.${pDomain}.dev"
      ResourceRecords:
        - !Sub "{{resolve:ssm:/sample/directory/ip0}}"
      TTL: 900
      Type: A
  workspaceDirectoryParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Directory ID for AWS Managed AD
      Name: /sample/directory/id
      Type: String
      Value: !Ref pDirectoryId
  WindowsFileSystemIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ID for FSX
      Name: /sample/fsx/id
      Type: String
      Value: !Ref WindowsFileSystem
  WindowsFileSystemDNSParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DNS for FSX
      Name: /sample/fsx/dns
      Type: String
      Value: !GetAtt WindowsFileSystem.DNSName
