AWSTemplateFormatVersion: 2010-09-09
Resources:
  AutomationRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws-us-gov:iam::aws:policy/AmazonEC2FullAccess"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      RoleName: sampleCentralServicesAutomationEC2Role
  ec2PatchingResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: "ec2PatchingResourceGroup"
      Description: "A group that is based on a tag query"
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters:
            - "AWS::EC2::Instance"
          TagFilters:
            - Key: "systemGroup"
              Values:
                - "Amazon Linux"
                - "Ubuntu"
                - "Red Hat Enterprise Linux"
  ec2RedHatResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: "ec2RedHatResourceGroup"
      Description: "A group that is based on a tag query"
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters:
            - "AWS::EC2::Instance"
          TagFilters:
            - Key: "systemGroup"
              Values:
                - "Red Hat Enterprise Linux"
  ec2DailyStartResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: "ec2DailyStartResourceGroup"
      Description: "A group that is based on a tag query"
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters:
            - "AWS::EC2::Instance"
          TagFilters:
            - Key: "ec2DailyStart"
              Values:
                - "true"
  ec2DailyStopResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: "ec2DailyStopResourceGroup"
      Description: "A group that is based on a tag query"
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters:
            - "AWS::EC2::Instance"
          TagFilters:
            - Key: "ec2DailyStop"
              Values:
                - "true"
  ec2PatchingWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to Patch Instances with Tag
      Duration: 4
      Name: ec2PatchingWindow
      Schedule: cron(00 6 ? * MON,FRI *)
      ScheduleTimezone: US/Pacific
  startInstanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to Start Instances with Tag
      Duration: 6
      Name: startInstanceWindow
      Schedule: cron(00 4 ? * MON-FRI *)
      ScheduleTimezone: US/Pacific
  stopInstanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to Stop Instances with Tag
      Duration: 6
      Name: stopInstanceWindow
      Schedule: cron(00 18 ? * * *)
      ScheduleTimezone: US/Pacific
  ec2RedHatWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to Run Compliance Scans on Red Hat Instances
      Duration: 4
      Name: ec2RedHatComplianceWindow
      Schedule: cron(00 6 ? * FRI *)
      ScheduleTimezone: US/Pacific
  ec2PatchingWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    DependsOn: ec2PatchingWindow
    Properties:
      WindowId: !Ref ec2PatchingWindow
      ResourceType: RESOURCE_GROUP
      Targets:
        - Key: resource-groups:Name
          Values:
            - ec2RedHatResourceGroup
      OwnerInformation: sample Automated EC2 Patching
      Name: ec2PatchingWindowTarget
      Description: A target for automatically running commands on Red Hat EC2 instances.
  ec2RedHatTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    DependsOn: ec2RedHatWindow
    Properties:
      WindowId: !Ref ec2RedHatWindow
      ResourceType: RESOURCE_GROUP
      Targets:
        - Key: resource-groups:Name
          Values:
            - ec2RedHatResourceGroup
      OwnerInformation: sample Automated EC2 Patching
      Name: ec2RedHatTarget
      Description: A target for running commands on RedHat EC2 instances.
  startInstanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    DependsOn: startInstanceWindow
    Properties:
      WindowId: !Ref startInstanceWindow
      ResourceType: RESOURCE_GROUP
      Targets:
        - Key: resource-groups:Name
          Values:
            - ec2DailyStartResourceGroup
      OwnerInformation: sample Automated EC2 Start
      Name: startInstanceWindowTarget
      Description: A target for automatically starting EC2 instances.
  stopInstanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    DependsOn: stopInstanceWindow
    Properties:
      WindowId: !Ref stopInstanceWindow
      ResourceType: RESOURCE_GROUP
      Targets:
        - Key: resource-groups:Name
          Values:
            - ec2DailyStopResourceGroup
      OwnerInformation: sample Automated EC2 Stop
      Name: stopInstanceWindowTarget
      Description: A target for automatically stopping EC2 instances.
  ec2PatchingRunCommandTask:
    Type: AWS::SSM::MaintenanceWindowTask
    DependsOn: ec2PatchingWindowTarget
    Properties:
      WindowId: !Ref ec2PatchingWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref ec2PatchingWindowTarget
      TaskType: RUN_COMMAND
      TaskArn: AWS-RunPatchBaseline
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            Operation:
              - Install
            RebootOption:
              - NoReboot
      MaxConcurrency: 7
      MaxErrors: 50
      Priority: 1
  startInstanceAutomationCommandTask:
    Type: AWS::SSM::MaintenanceWindowTask
    DependsOn: startInstanceWindowTarget
    Properties:
      WindowId: !Ref startInstanceWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref startInstanceWindowTarget
      TaskType: AUTOMATION
      TaskArn: AWS-StartEC2Instance
      TaskInvocationParameters:
        MaintenanceWindowAutomationParameters:
          Parameters:
            InstanceId:
              - "{{RESOURCE_ID}}"
            AutomationAssumeRole:
              - !GetAtt AutomationRole.Arn
      MaxConcurrency: 7
      MaxErrors: 7
      Priority: 5
  stopInstanceAutomationCommandTask:
    Type: AWS::SSM::MaintenanceWindowTask
    DependsOn: stopInstanceWindowTarget
    Properties:
      WindowId: !Ref stopInstanceWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref stopInstanceWindowTarget
      TaskType: AUTOMATION
      TaskArn: AWS-StopEC2Instance
      TaskInvocationParameters:
        MaintenanceWindowAutomationParameters:
          Parameters:
            InstanceId:
              - "{{RESOURCE_ID}}"
            AutomationAssumeRole:
              - !GetAtt AutomationRole.Arn
      MaxConcurrency: 7
      MaxErrors: 7
      Priority: 5
  ec2RedHatInsightsRunCommandTask:
    Type: AWS::SSM::MaintenanceWindowTask
    DependsOn: ec2RedHatTarget
    Properties:
      WindowId: !Ref ec2RedHatWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref ec2RedHatTarget
      TaskType: RUN_COMMAND
      TaskArn: AWS-RunShellScript
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            commands:
              - insights-client --compliance
      MaxConcurrency: 7
      MaxErrors: 50
      Priority: 1
  backupRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by Backup
    Properties:
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
        Version: "2012-10-17"
      Path: /
  backupKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encryption key for daily"
      EnableKeyRotation: True
      Enabled: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              "AWS": { "Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" }
            Action:
              - kms:*
            Resource: "*"
  backupVaultWithDailyBackups:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: "BackupVaultWithDailyBackups"
      EncryptionKeyArn: !GetAtt backupKMSKey.Arn
  backupPlanWithDailyBackups:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: "BackupPlanWithDailyBackups"
        BackupPlanRule:
          - RuleName: "RuleForDailyBackups"
            TargetBackupVault: !Ref backupVaultWithDailyBackups
            ScheduleExpression: "cron(0 2 ? * MON-FRI *)"
            Lifecycle:
              DeleteAfterDays: 7
    DependsOn: backupVaultWithDailyBackups
  tagBasedBackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupSelection:
        SelectionName: "TagBasedBackupSelection"
        IamRoleArn: !GetAtt backupRole.Arn
        Resources:
        - "arn:aws-us-gov:ec2:*:*:instance/*"
        - "arn:aws-us-gov:ec2:*:*:volume/*"
        Conditions:
          StringEquals:
          - ConditionKey: "aws:ResourceTag/dailyBackup"
            ConditionValue: "true"
      BackupPlanId: !Ref backupPlanWithDailyBackups
    DependsOn: backupPlanWithDailyBackups
  ec2MonthlyRestartResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: "ec2MonthlyRestartResourceGroup"
      Description: "A group that is based on a tag query"
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters:
            - "AWS::EC2::Instance"
          TagFilters:
            - Key: "ec2DailyStop"
              Values:
                - "false"
  restartInstanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to Restart Instances with Tag
      Duration: 6
      Name: restartInstanceWindow
      Schedule: cron(00 2 ? * 2#1 *)
      ScheduleTimezone: US/Pacific
  restartInstanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    DependsOn: restartInstanceWindow
    Properties:
      WindowId: !Ref restartInstanceWindow
      ResourceType: RESOURCE_GROUP
      Targets:
        - Key: resource-groups:Name
          Values:
            - ec2MonthlyRestartResourceGroup
      OwnerInformation: sample Automated EC2 Restart
      Name: restartInstanceWindowTarget
      Description: A target for automatically restarting EC2 instances.
  restartInstanceAutomationCommandTask:
    Type: AWS::SSM::MaintenanceWindowTask
    DependsOn: restartInstanceWindowTarget
    Properties:
      WindowId: !Ref restartInstanceWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref restartInstanceWindowTarget
      TaskType: AUTOMATION
      TaskArn: AWS-RestartEC2Instance
      TaskInvocationParameters:
        MaintenanceWindowAutomationParameters:
          Parameters:
            InstanceId:
              - "{{RESOURCE_ID}}"
            AutomationAssumeRole:
              - !GetAtt AutomationRole.Arn
      MaxConcurrency: 7
      MaxErrors: 7
      Priority: 5
  amazonLinuxPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: AmazonLinuxDefaultPatchBaseline
      Description: Default Patch Baseline for Amazon Linux.
      DefaultBaseline: true
      ApprovalRules:
        PatchRules:
        - ApproveAfterDays: 1
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: CLASSIFICATION
              Values:
              - Security
            - Key: SEVERITY
              Values:
              - Critical
              - Important
        - ApproveAfterDays: 7
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: CLASSIFICATION
              Values:
              - Security
            - Key: SEVERITY
              Values:
              - Medium
              - Low
        - ApproveAfterDays: 1
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: CLASSIFICATION
              Values:
              - Bugfix
      ApprovedPatches: []
      ApprovedPatchesComplianceLevel: UNSPECIFIED
      ApprovedPatchesEnableNonSecurity: false
      GlobalFilters:
        PatchFilters:
        - Key: PRODUCT
          Values:
          - '*'
      OperatingSystem: AMAZON_LINUX
      PatchGroups:
      - Amazon Linux
      RejectedPatches: []
      RejectedPatchesAction: ALLOW_AS_DEPENDENCY
      Sources: []
  redHatPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: RedHatDefaultPatchBaseline
      Description: Default Patch Baseline for Redhat Enterprise Linux
      DefaultBaseline: true
      ApprovalRules:
        PatchRules:
        - ApproveAfterDays: 1
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: CLASSIFICATION
              Values:
              - Security
            - Key: SEVERITY
              Values:
              - Critical
              - Important
        - ApproveAfterDays: 7
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: CLASSIFICATION
              Values:
              - Security
            - Key: SEVERITY
              Values:
              - Moderate
              - Low
        - ApproveAfterDays: 1
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: CLASSIFICATION
              Values:
              - Bugfix
      ApprovedPatches: []
      ApprovedPatchesComplianceLevel: UNSPECIFIED
      ApprovedPatchesEnableNonSecurity: false
      GlobalFilters:
        PatchFilters:
        - Key: PRODUCT
          Values:
          - '*'
      OperatingSystem: REDHAT_ENTERPRISE_LINUX
      PatchGroups:
      - Red Hat Enterprise Linux
      RejectedPatches: []
      RejectedPatchesAction: ALLOW_AS_DEPENDENCY
      Sources: []
  ubuntuPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: UbuntuDefaultPatchBaseline
      Description: Default Patch Baseline for Ubuntu
      DefaultBaseline: true
      ApprovalRules:
        PatchRules:
        - ApproveAfterDays: 1
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: PRIORITY
              Values:
              - Required
              - Important
        - ApproveAfterDays: 7
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
            - Key: PRIORITY
              Values:
              - Standard
      ApprovedPatches: []
      ApprovedPatchesComplianceLevel: UNSPECIFIED
      ApprovedPatchesEnableNonSecurity: false
      GlobalFilters:
        PatchFilters:
        - Key: PRODUCT
          Values:
          - '*'
      OperatingSystem: UBUNTU
      PatchGroups:
      - Ubuntu
      RejectedPatches: []
      RejectedPatchesAction: ALLOW_AS_DEPENDENCY
      Sources: []
  windowsPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: WindowsDefaultPatchBaseline
      Description: Default Patch Baseline for Windows
      DefaultBaseline: true
      ApprovalRules:
        PatchRules:
        - ApproveAfterDays: 1
          ComplianceLevel: UNSPECIFIED
          EnableNonSecurity: false
          PatchFilterGroup:
            PatchFilters:
              - Key: PATCH_SET
                Values:
                - OS
              - Key: CLASSIFICATION
                Values:
                - CriticalUpdates
                - SecurityUpdates
              - Key: MSRC_SEVERITY
                Values:
                - Critical
                - Important
      ApprovedPatches: []
      ApprovedPatchesComplianceLevel: UNSPECIFIED
      ApprovedPatchesEnableNonSecurity: false
      GlobalFilters:
        PatchFilters:
        - Key: PRODUCT
          Values:
          - '*'
      OperatingSystem: WINDOWS
      PatchGroups:
      - Windows
      RejectedPatches: []
      RejectedPatchesAction: ALLOW_AS_DEPENDENCY
      Sources: []