AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpcId:
    Type: AWS::EC2::VPC::Id
  subnet0:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet the ELB, VPC Endpoint Services and VPC Endpoints will be deployed. Must be within the VPC of the provided vpcId parameter.
  subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet the ELB. Must be in a different Availability Zone of the subnet0 parameter.
  existingELB:
    Type: String
    Description: Do you have an existing Elastic Load Balancer for the Kubernetes cluster the Edge is deployed to?
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  existingELBARN:
    Type: String
    Description: If you have an existing ELB integrated with your Kubernetes cluster, input the ARN.
    Default: "none"
  whichUpstream:
    Type: String
    Description: Are you attempting to connect to the Testing Upstream or the Production Upstream?
    Default: "Testing"
    AllowedValues:
      - "Testing"
      - "Production"
  sample:
    Type: String
    Description: Is this being deployed to sample?
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Information"
        Parameters:
          - vpcId
          - subnet0
          - subnet1
      - Label:
          default: "Integration Information"
        Parameters:
          - whichUpstream
          - existingELB
          - existingELBARN
Conditions:
  deployELB: !Equals
    - !Ref existingELB
    - "false"
  testingUpstream: !Equals
    - !Ref whichUpstream
    - "Testing"
  sample: !Equals
    - !Ref sample
    - "true"
  Notsample: !Not
    - Condition: sample
Resources:
# Resources for VPC Endpoint Service to Edge Kubernetes Deployments
  ElasticLoadBalancingV2LoadBalancer:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      IpAddressType: "ipv4"
      SecurityGroups: []
      Subnets:
      - !Ref subnet0
      - !Ref subnet1
      Type: "network"
      Scheme: "internal"
      Name: !Sub "${AWS::StackName}-lb"
  ElasticLoadBalancingV2ListenerHTTPS0:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      ListenerAttributes:
      - Value: "350"
        Key: "tcp.idle_timeout.seconds"
      Protocol: "TCP"
      LoadBalancerArn:
        Ref: "ElasticLoadBalancingV2LoadBalancer"
      DefaultActions:
      - TargetGroupArn:
          Ref: "ElasticLoadBalancingV2TargetGroupHTTPS0"
        Type: forward
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn:
              Ref: "ElasticLoadBalancingV2TargetGroupHTTPS0"
      Port: 443
  ElasticLoadBalancingV2TargetGroupHTTPS0:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      IpAddressType: "ipv4"
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: "200-399"
      HealthCheckPath: "/healthz"
      Port: 443
      HealthCheckEnabled: true
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 6
      Name: !Sub "${AWS::StackName}-https"
      VpcId: !Ref vpcId
      HealthyThresholdCount: 5
      HealthCheckProtocol: "HTTP"
      TargetGroupAttributes:
      - Value: "source_ip"
        Key: "stickiness.type"
      - Value: "1"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.count"
      - Value: "use_load_balancer_configuration"
        Key: "load_balancing.cross_zone.enabled"
      - Value: "off"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.percentage"
      - Value: "false"
        Key: "stickiness.enabled"
      - Value: "off"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.percentage"
      - Value: "0"
        Key: "target_health_state.unhealthy.draining_interval_seconds"
      - Value: "300"
        Key: "deregistration_delay.timeout_seconds"
      - Value: "1"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.count"
      - Value: "true"
        Key: "preserve_client_ip.enabled"
      - Value: "false"
        Key: "proxy_protocol_v2.enabled"
      - Value: "false"
        Key: "deregistration_delay.connection_termination.enabled"
      - Value: "true"
        Key: "target_health_state.unhealthy.connection_termination.enabled"
      TargetType: "instance"
      HealthCheckPort: "80"
      Protocol: "TCP"

  ElasticLoadBalancingV2TargetGroupHTTPS1:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      IpAddressType: "ipv4"
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: "200-399"
      HealthCheckPath: "/"
      Port: 8443
      HealthCheckEnabled: true
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 6
      Name: !Sub "${AWS::StackName}-security"
      VpcId: !Ref vpcId
      HealthyThresholdCount: 5
      HealthCheckProtocol: "HTTP"
      TargetGroupAttributes:
      - Value: "source_ip"
        Key: "stickiness.type"
      - Value: "1"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.count"
      - Value: "use_load_balancer_configuration"
        Key: "load_balancing.cross_zone.enabled"
      - Value: "off"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.percentage"
      - Value: "false"
        Key: "stickiness.enabled"
      - Value: "off"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.percentage"
      - Value: "0"
        Key: "target_health_state.unhealthy.draining_interval_seconds"
      - Value: "300"
        Key: "deregistration_delay.timeout_seconds"
      - Value: "1"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.count"
      - Value: "true"
        Key: "preserve_client_ip.enabled"
      - Value: "false"
        Key: "proxy_protocol_v2.enabled"
      - Value: "false"
        Key: "deregistration_delay.connection_termination.enabled"
      - Value: "true"
        Key: "target_health_state.unhealthy.connection_termination.enabled"
      TargetType: "instance"
      HealthCheckPort: "traffic-port"
      Protocol: "TCP"

  ElasticLoadBalancingV2ListenerHTTPS1:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      ListenerAttributes:
      - Value: "350"
        Key: "tcp.idle_timeout.seconds"
      Protocol: "TCP"
      LoadBalancerArn:
        Ref: "ElasticLoadBalancingV2LoadBalancer"
      DefaultActions:
      - TargetGroupArn:
          Ref: "ElasticLoadBalancingV2TargetGroupHTTPS1"
        Type: forward
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn:
              Ref: "ElasticLoadBalancingV2TargetGroupHTTPS1"
      Port: 8443
  ElasticLoadBalancingV2TargetGroupHTTPS2:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      IpAddressType: "ipv4"
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: "200-399"
      HealthCheckPath: "/"
      Port: 6443
      HealthCheckEnabled: true
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 6
      Name: !Sub "${AWS::StackName}-api"
      VpcId: !Ref vpcId
      HealthyThresholdCount: 5
      HealthCheckProtocol: "HTTP"
      TargetGroupAttributes:
      - Value: "source_ip"
        Key: "stickiness.type"
      - Value: "1"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.count"
      - Value: "use_load_balancer_configuration"
        Key: "load_balancing.cross_zone.enabled"
      - Value: "off"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.percentage"
      - Value: "false"
        Key: "stickiness.enabled"
      - Value: "off"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.percentage"
      - Value: "0"
        Key: "target_health_state.unhealthy.draining_interval_seconds"
      - Value: "300"
        Key: "deregistration_delay.timeout_seconds"
      - Value: "1"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.count"
      - Value: "true"
        Key: "preserve_client_ip.enabled"
      - Value: "false"
        Key: "proxy_protocol_v2.enabled"
      - Value: "false"
        Key: "deregistration_delay.connection_termination.enabled"
      - Value: "true"
        Key: "target_health_state.unhealthy.connection_termination.enabled"
      TargetType: "instance"
      HealthCheckPort: "traffic-port"
      Protocol: "TCP"

  ElasticLoadBalancingV2ListenerHTTPS2:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      ListenerAttributes:
      - Value: "350"
        Key: "tcp.idle_timeout.seconds"
      Protocol: "TCP"
      LoadBalancerArn:
        Ref: "ElasticLoadBalancingV2LoadBalancer"
      DefaultActions:
      - TargetGroupArn:
          Ref: "ElasticLoadBalancingV2TargetGroupHTTPS2"
        Type: forward
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn:
              Ref: "ElasticLoadBalancingV2TargetGroupHTTPS2"
      Port: 6443
  ElasticLoadBalancingV2TargetGroupHTTPS3:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      IpAddressType: "ipv4"
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: "200-399"
      HealthCheckPath: "/"
      Port: 5000
      HealthCheckEnabled: true
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 6
      Name: !Sub "${AWS::StackName}-docker"
      VpcId: !Ref vpcId
      HealthyThresholdCount: 5
      HealthCheckProtocol: "HTTP"
      TargetGroupAttributes:
      - Value: "source_ip"
        Key: "stickiness.type"
      - Value: "1"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.count"
      - Value: "use_load_balancer_configuration"
        Key: "load_balancing.cross_zone.enabled"
      - Value: "off"
        Key: "target_group_health.dns_failover.minimum_healthy_targets.percentage"
      - Value: "false"
        Key: "stickiness.enabled"
      - Value: "off"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.percentage"
      - Value: "0"
        Key: "target_health_state.unhealthy.draining_interval_seconds"
      - Value: "300"
        Key: "deregistration_delay.timeout_seconds"
      - Value: "1"
        Key: "target_group_health.unhealthy_state_routing.minimum_healthy_targets.count"
      - Value: "true"
        Key: "preserve_client_ip.enabled"
      - Value: "false"
        Key: "proxy_protocol_v2.enabled"
      - Value: "false"
        Key: "deregistration_delay.connection_termination.enabled"
      - Value: "true"
        Key: "target_health_state.unhealthy.connection_termination.enabled"
      TargetType: "instance"
      HealthCheckPort: "traffic-port"
      Protocol: "TCP"

  ElasticLoadBalancingV2ListenerHTTPS3:
    Condition: deployELB
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      ListenerAttributes:
      - Value: "350"
        Key: "tcp.idle_timeout.seconds"
      Protocol: "TCP"
      LoadBalancerArn:
        Ref: "ElasticLoadBalancingV2LoadBalancer"
      DefaultActions:
      - TargetGroupArn:
          Ref: "ElasticLoadBalancingV2TargetGroupHTTPS3"
        Type: forward
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn:
              Ref: "ElasticLoadBalancingV2TargetGroupHTTPS3"
      Port: 5000
  EC2VPCEndpointService:
    Type: "AWS::EC2::VPCEndpointService"
    Properties:
      NetworkLoadBalancerArns:
        !If
          - deployELB
          - - !Ref ElasticLoadBalancingV2LoadBalancer
          - - !Ref existingELBARN
      SupportedIpAddressTypes:
      - "ipv4"
      AcceptanceRequired: false
      GatewayLoadBalancerArns: []
      Tags:
      - Value: "edge-ingress-endpoint-service"
        Key: "Name"
  ELBServicePermissions:
    Type: AWS::EC2::VPCEndpointServicePermissions
    DeletionPolicy: Retain
    Properties:
      ServiceId: !GetAtt EC2VPCEndpointService.ServiceId
      AllowedPrincipals:
        - arn:aws-us-gov:iam::<PLACEHOLDER>:root
# Resources for VPC Endpoint to Connections to sample Upstream Servers
  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "sampleEndpointSecurityGroup"
      GroupName: !Sub "${AWS::StackName}-SG"
      VpcId: !Ref vpcId
      SecurityGroupIngress:
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "tcp"
        FromPort: 443
        ToPort: 443
      SecurityGroupEgress:
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "-1"
        FromPort: -1
        ToPort: -1
  EC2VPCEndpointOceApp:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      IpAddressType: "ipv4"
      SecurityGroupIds:
      - !Ref EC2SecurityGroup
      SubnetIds:
      - !Ref subnet0
      - !Ref subnet1
      VpcId: !Ref vpcId
      ServiceName: !If
          - testingUpstream
          - "com.amazonaws.vpce.us-gov-west-1.vpce-svc-02146cbdec50e7c1d"
          - "com.amazonaws.vpce.us-gov-west-1.vpce-svc-0411f4e8856738d7e"
      VpcEndpointType: "Interface"
      Tags:
      - Value: "sample-downstream-app-endpoint"
        Key: "Name"
  EC2VPCEndpointOceSec:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      IpAddressType: "ipv4"
      SecurityGroupIds:
      - !Ref EC2SecurityGroup
      SubnetIds:
      - !Ref subnet0
      - !Ref subnet1
      VpcId: !Ref vpcId
      ServiceName: !If
        - testingUpstream
        - "com.amazonaws.vpce.us-gov-west-1.vpce-svc-062f138samplebd6037c6"
        - "com.amazonaws.vpce.us-gov-west-1.vpce-svc-029f3a4d587fa73d1"
      VpcEndpointType: "Interface"
      Tags:
      - Value: "sample-downstream-sec-endpoint"
        Key: "Name"
  EC2VPCEndpointOceVst:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      IpAddressType: "ipv4"
      SecurityGroupIds:
      - !Ref EC2SecurityGroup
      SubnetIds:
      - !Ref subnet0
      - !Ref subnet1
      VpcId: !Ref vpcId
      ServiceName: !If
        - testingUpstream
        - "com.amazonaws.vpce.us-gov-west-1.vpce-svc-0bfb30836d165d9ce"
        - "com.amazonaws.vpce.us-gov-west-1.vpce-svc-0f8fafd4576f82f90"
      VpcEndpointType: "Interface"
      Tags:
      - Value: "sample-downstream-vst-endpoint"
        Key: "Name"
  Route53HostedZone:
    Type: "AWS::Route53::HostedZone"
    Condition: Notsample
    Properties:
      VPCs:
      - VPCRegion: "us-gov-west-1"
        VPCId: !Ref vpcId
      HostedZoneConfig:
        Comment: ""
      Name: ".dev."
  ServerRecordOceApp:
    Type: AWS::Route53::RecordSetGroup
    Condition: Notsample
    Properties:
      Comment: Alias record for the API server
      HostedZoneId: !Ref Route53HostedZone
      RecordSets:
        - Name: !If
          - testingUpstream
          - "app.0.downstream.uptest.dev"
          - "app.0.downstream.upprod.dev"
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !Select [1, !Split [ ":", !Select [0, !GetAtt EC2VPCEndpointOceApp.DnsEntries ] ] ]
  ServerRecordOceSec:
    Type: AWS::Route53::RecordSetGroup
    Condition: Notsample
    Properties:
      Comment: Alias record for the API server
      HostedZoneId: !Ref Route53HostedZone
      RecordSets:
        - Name: !If
          - testingUpstream
          - "sec.0.downstream.uptest.dev"
          - "sec.0.downstream.upprod.dev"
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !Select [1, !Split [ ":", !Select [0, !GetAtt EC2VPCEndpointOceSec.DnsEntries ] ] ]
  ServerRecordOceVst:
    Type: AWS::Route53::RecordSetGroup
    Condition: Notsample
    Properties:
      Comment: Alias record for the API server
      HostedZoneId: !Ref Route53HostedZone
      RecordSets:
        - Name: !If
          - testingUpstream
          - "viewer.0.downstream.uptest.dev"
          - "viewer.0.downstream.upprod.dev"
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !Select [1, !Split [ ":", !Select [0, !GetAtt EC2VPCEndpointOceviewer.DnsEntries ] ] ]